version: "3.9"
services:

  postgres:
    image: postgres:16.2-alpine3.18
    environment:
     - POSTGRES_USER=schooluser
     - POSTGRES_DB=studentdb
     - POSTGRES_PASSWORD=school123
    ports:
      - "5432:5432"

  student-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - DB_SOURCE=postgresql://schooluser:school123@postgres:5432/studentdb?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/student-go-api"]