version: '3.8'

services:
  go-rest-api:
    env_file:
      - app.env
    depends_on:
      - postgres-db
    build:
      context: .
    container_name: go-rest-server
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
  
  postgres-db:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - "5432:5432"
    env_file:
      - app.env