service:
  port: 9187
  type: ClusterIP

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Database connection details - retrieved from HashiCorp Vault via ESO
env:
  - name: DATA_SOURCE_USER
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_USER
  - name: DATA_SOURCE_PASS
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_PASS
  - name: DATA_SOURCE_DB
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_DB
  - name: DATA_SOURCE_HOST
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_HOST
  - name: DATA_SOURCE_PORT
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_PORT
  - name: DATA_SOURCE_URI
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: DATA_SOURCE_URI
  # - name: DATA_SOURCE_URI
  #   value: postgresql://$(DATA_SOURCE_USER):$(DATA_SOURCE_PASS)@$(DATA_SOURCE_HOST):$(DATA_SOURCE_PORT)/$(DATA_SOURCE_DB)?sslmode=disable

# Prometheus scrape configuration
prometheus:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"