# promtail configuration to send only application logs to Loki

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: student-app-logs
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: student-api-app
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            regex: student-api-ns
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: keep
            target_label: student-api-deployment-776bfdbdd-5nkcl
        pipeline_stages:
          - docker: {}