# SecretSctore For Database
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: student-api-ns
spec:
  provider:
    vault:
      server: "http://10.111.217.113:8200"
      path: "secretdata"
      version: "v2"
      auth:
        # kubernetes:
        #   role: "eso-role"
        #   serviceAccountRef:
        #     name: "vault"
        #     namespace: "vault-ns"
        tokenSecretRef:
          name: vault-token
          key: token
          # namespace: vault-ns

# SecretStore for API app
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: api-backend
  namespace: student-api-ns
spec:
  provider:
    vault:
      server: "http://10.111.217.113:8200"
      path: "apidata"
      version: "v2"
      auth:
        # kubernetes:
        #   role: "eso-role"
        #   serviceAccountRef:
        #     name: "vault"
        #     namespace: "vault-ns"
        tokenSecretRef:
          name: vault-token
          key: token
          # namespace: vault-ns