apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student-api-ns
  name: postgres-db-deployment
  labels:
    app: postgres-db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-app
  template:
    metadata:
      labels:
        app: postgres-db-app
    spec:
      nodeSelector:
        database: "database-node"
      containers:
      - name: postgres-db
        image: postgres:16.2-alpine3.18
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB        
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: student-api-ns
  name: postgres-service
  labels:
    name: postgres-db-service
spec:
  selector:
    app: postgres-db-app
  ports:
  - port: 5432
    targetPort: 5432
