apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student-api-ns
  name: student-api-deployment
  labels:
    app: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api-app
  template:
    metadata:
      labels:
        name: student-api
        app: student-api-app
    spec:
      nodeSelector:
        application: application-node
      containers:
      - name: student-api-app
        image: juw0n/student-go-api:v1.0.0
        env:
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_DRIVER
        - name: DB_SOURCE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_SOURCE
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB        
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8000