# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}

---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.persistentVolumeClaim.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
  accessModes:
    {{- range .Values.persistentVolumeClaim.accessModes }}
    - {{ . }}
    {{- end }}
