# Default values for vault-eso.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dbSecretStore:
  name: vault-backend
  namespace: student-api-ns
  vault:
    server: "http://10.104.105.102:8200"
    path: "secretdata"
    version: "v2"
    auth:
      tokenSecretRef:
        name: vault-token
        key: token


apiSecretStore:
  name: api-backend
  namespace: student-api-ns
  vault:
    server: "http://10.104.105.102:8200"
    path: "apidata"
    version: "v2"
    auth:
      tokenSecretRef:
        name: vault-token
        key: token

metricsSecretStore:
  name: metrics-backend
  namespace: student-api-ns
  vault:
    server: "http://10.104.105.102:8200"
    path: "metricsexporter"
    version: "v2"
    auth:
      tokenSecretRef:
        name: vault-token
        key: token

metricsDBSecretStore:
  name: metrics-db-backend
  namespace: observability
  vault:
    server: "http://10.104.105.102:8200"
    path: "metricsexporter"
    version: "v2"
    auth:
      tokenSecretRef:
        name: vault-token
        key: token


dbExternalSecretStore:
  name: postgres-secrets
  namespace: student-api-ns
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credential
    creationPolicy: Owner
  data:
    POSTGRES_USER:
      key: secretdata/data/postgresql
      property: POSTGRES_USER
    POSTGRES_PASSWORD:
      key: secretdata/data/postgresql
      property: POSTGRES_PASSWORD
    POSTGRES_DB:
      key: secretdata/data/postgresql
      property: POSTGRES_DB


apiExternalSecretStore:
  name: api-secrets
  namespace: student-api-ns
  refreshInterval: "1h"
  secretStoreRef:
    name: api-backend
    kind: SecretStore
  target:
    name: api-credential
    creationPolicy: Owner
  data:
    DB_DRIVER:
      key: apidata/data/studentapi
      property: DB_DRIVER
    DB_SOURCE:
      key: apidata/data/studentapi
      property: DB_SOURCE


metricsExternalSecretStore:
  name: metrics-secrets
  namespace: student-api-ns
  refreshInterval: "1h"
  secretStoreRef:
    name: metrics-backend
    kind: SecretStore
  target:
    name: metrics-credential
    creationPolicy: Owner
  data:
    DATA_SOURCE_USER:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_USER
    DATA_SOURCE_PASS:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_PASS
    DATA_SOURCE_DB:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_DB
    DATA_SOURCE_HOST:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_HOST
    DATA_SOURCE_PORT:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_PORT
    DATA_SOURCE_URI:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_URI

metricsDBExternalSecretStore:
  name: metrics-db-secrets
  namespace: observability
  refreshInterval: "1h"
  secretStoreRef:
    name: metrics-db-backend
    kind: SecretStore
  target:
    name: metrics-db-credential
    creationPolicy: Owner
  data:
    DATA_SOURCE_USER:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_USER
    DATA_SOURCE_PASS:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_PASS
    DATA_SOURCE_DB:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_DB
    DATA_SOURCE_HOST:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_HOST
    DATA_SOURCE_PORT:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_PORT
    DATA_SOURCE_URI:
      key: metricsexporter/data/dbexporter
      property: DATA_SOURCE_URI