// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Course struct {
	CourseID   int64          `json:"course_id"`
	CourseName string         `json:"course_name"`
	Instructor sql.NullString `json:"instructor"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Enrollment struct {
	EnrollmentID   int64     `json:"enrollment_id"`
	EnrollmentDate time.Time `json:"enrollment_date"`
	StudentID      int32     `json:"student_id"`
	CourseID       int32     `json:"course_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Student struct {
	StudentID    int64     `json:"student_id"`
	FirstName    string    `json:"first_name"`
	MiddleName   string    `json:"middle_name"`
	LastName     string    `json:"last_name"`
	Gender       string    `json:"gender"`
	DateOfBirth  time.Time `json:"date_of_birth"`
	PhoneNumber  string    `json:"phone_number"`
	Email        string    `json:"email"`
	YearOfEnroll int32     `json:"year_of_enroll"`
	Country      string    `json:"country"`
	Major        string    `json:"major"`
	CreatedAt    time.Time `json:"created_at"`
}
