---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: student-api-ns
data:
  DATABASE_URL: postgres-db-service 

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: student-api-ns
data:
  POSTGRES_DB: c3R1ZGVudGRi  #studentdb
  POSTGRES_USER: c2Nob29sdXNlcg== #schooluser
  POSTGRES_PASSWORD: c2Nob29sMTIz  #school123

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: student-api-ns
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: ./data/postgresql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: student-api-ns
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: student-api-ns
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      nodeSelector:
        kubernetes.io/hostname: dependent_services
      containers:
      - name: postgresql-db
        image: postgres:16.2-alpine3.18
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: student-api-ns
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432  
    targetPort: 5432
    nodePort: 30110 
  type: NodePort