apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
  namespace: student-api-ns
spec:
  provider:
    vault:
      server: "http://10.100.190.37:8200"
      path: "secretdata"
      version: "v2"
      auth:
        # kubernetes:
        #   role: eso-role
        #   serviceAccountRef:
        #     name: vault
        #     namespace: vault-ns
        # This additional token can be used if the above serviceAccountRef causes issues
        tokenSecretRef:
          name: vault-token
          key: token