apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: student-api-ns
  name: postgres-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
        path: "/data/postgresData"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: student-api-ns
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
