apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: student-api-ns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: api-backend
    kind: SecretStore
  target:
    name: api-credential
    creationPolicy: Owner
  data:
    - secretKey: DB_DRIVER
      remoteRef:
        key: apidata/data/studentapi
        property: DB_DRIVER
    - secretKey: DB_SOURCE
      remoteRef:
        key: apidata/data/studentapi
        property: DB_SOURCE