apiVersion: v1
kind: Service
metadata:
  namespace: student-api-ns
  name: student-api-service
  labels:
    name: student-api-service
spec:
  selector:
    app: student-api-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100
  type: NodePort