service:
  port: 9187
  type: ClusterIP

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Database connection details - retrieved from HashiCorp Vault via ESO
env:
  - name: DATA_SOURCE_USER
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: POSTGRES_USER
  - name: DATA_SOURCE_PASS
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: POSTGRES_PASSWORD
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: POSTGRES_DB
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: POSTGRES_HOST
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: metrics-credential
        key: POSTGRES_PORT
  - name: DATA_SOURCE_NAME
    value: postgresql://$(DATA_SOURCE_USER):$(DATA_SOURCE_PASS)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable

# Prometheus scrape configuration
prometheus:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"

# ServiceMonitor for Prometheus Operator
serviceMonitor:
  enabled: true
  interval: 10s
  scrapeTimeout: 10s
  selector:
    matchLabels:
      release: prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 10s