# external Secrets Store for DB
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: student-api-ns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credential
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secretdata/data/postgresql
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secretdata/data/postgresql
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secretdata/data/postgresql
        property: POSTGRES_DB

# external Secrets Store for API
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: student-api-ns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: api-backend
    kind: SecretStore
  target:
    name: api-credential
    creationPolicy: Owner
  data:
    - secretKey: DB_DRIVER
      remoteRef:
        key: apidata/data/studentapi
        property: DB_DRIVER
    - secretKey: DB_SOURCE
      remoteRef:
        key: apidata/data/studentapi
        property: DB_SOURCE

# external Secrets Store for DB Metrics Exporter
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metrics-secrets
  namespace: student-api-ns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: metrics-backend
    kind: SecretStore
  target:
    name: metrics-credential
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: metricsexporter/data/dbexporter
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: metricsexporter/data/dbexporter
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: metricsexporter/data/dbexporter
        property: POSTGRES_DB