# external Secrets Store for DB
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.dbExternalSecretStore.name }}
  namespace: {{ .Values.dbExternalSecretStore.namespace }}
spec:
  refreshInterval: {{ .Values.dbExternalSecretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.dbExternalSecretStore.secretStoreRef.name }}
    kind: {{ .Values.dbExternalSecretStore.secretStoreRef.kind }}
  target:
    name: {{ .Values.dbExternalSecretStore.target.name }}
    creationPolicy: {{ .Values.dbExternalSecretStore.target.creationPolicy }}
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.dbExternalSecretStore.data.POSTGRES_USER.key }}
        property: {{ .Values.dbExternalSecretStore.data.POSTGRES_USER.property }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.dbExternalSecretStore.data.POSTGRES_PASSWORD.key }}
        property: {{ .Values.dbExternalSecretStore.data.POSTGRES_PASSWORD.property }}
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.dbExternalSecretStore.data.POSTGRES_DB.key }}
        property: {{ .Values.dbExternalSecretStore.data.POSTGRES_DB.property }}
        
# external Secrets Store for API
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.apiExternalSecretStore.name }}
  namespace: {{ .Values.apiExternalSecretStore.namespace }}
spec:
  refreshInterval: {{ .Values.apiExternalSecretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.apiExternalSecretStore.secretStoreRef.name }}
    kind: {{ .Values.apiExternalSecretStore.secretStoreRef.kind }}
  target:
    name: {{ .Values.apiExternalSecretStore.target.name }}
    creationPolicy: {{ .Values.apiExternalSecretStore.target.creationPolicy }}
  data:
    - secretKey: DB_DRIVER
      remoteRef:
        key: {{ .Values.apiExternalSecretStore.data.DB_DRIVER.key }}
        property: {{ .Values.apiExternalSecretStore.data.DB_DRIVER.property }}
    - secretKey: DB_SOURCE
      remoteRef:
        key: {{ .Values.apiExternalSecretStore.data.DB_SOURCE.key }}
        property: {{ .Values.apiExternalSecretStore.data.DB_SOURCE.property }}

---
# external Secrets Store for metrics-exporter
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.metricsExternalSecretStore.name }}
  namespace: {{ .Values.metricsExternalSecretStore.namespace }}
spec:
  refreshInterval: {{ .Values.metricsExternalSecretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.metricsExternalSecretStore.secretStoreRef.name }}
    kind: {{ .Values.metricsExternalSecretStore.secretStoreRef.kind }}
  target:
    name: {{ .Values.metricsExternalSecretStore.target.name }}
    creationPolicy: {{ .Values.metricsExternalSecretStore.target.creationPolicy }}
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.metricsExternalSecretStore.data.POSTGRES_USER.key }}
        property: {{ .Values.metricsExternalSecretStore.data.POSTGRES_USER.property }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.metricsExternalSecretStore.data.POSTGRES_PASSWORD.key }}
        property: {{ .Values.metricsExternalSecretStore.data.POSTGRES_PASSWORD.property }}
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.metricsExternalSecretStore.data.POSTGRES_DB.key }}
        property: {{ .Values.metricsExternalSecretStore.data.POSTGRES_DB.property }}