# SecretSctore For Database
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.dbSecretStore.name }}
  namespace: {{ .Values.dbSecretStore.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.dbSecretStore.vault.server }}
      path: {{ .Values.dbSecretStore.vault.path }}
      version: {{ .Values.dbSecretStore.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.dbSecretStore.vault.auth.tokenSecretRef.name }}
          key: {{ .Values.dbSecretStore.vault.auth.tokenSecretRef.key }}

# SecretStore for API app
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.apiSecretStore.name }}
  namespace: {{ .Values.apiSecretStore.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.apiSecretStore.vault.server }}
      path: {{ .Values.apiSecretStore.vault.path }}
      version: {{ .Values.apiSecretStore.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.apiSecretStore.vault.auth.tokenSecretRef.name }}
          key: {{ .Values.apiSecretStore.vault.auth.tokenSecretRef.key }}
