name: Update Helm Image Tag

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          IMAGE_TAG="v1.0.1" # Update this to the latest tag

      - name: Update API image tag in values.yaml
        run: |
          sed -i "s/tag: .*/tag: $IMAGE_TAG/" helm/charts/api/values.yaml

      - name: Update DB image tag in values.yaml
        run: |
          sed -i "s/tag: .*/tag: $IMAGE_TAG/" helm/charts/db/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add helm/charts/api/values.yaml helm/charts/db/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin main