name: Deploy-to-Docker

on:
    push:
      branches:
        - "main"

jobs:
  build:
    # runs-on: ubuntu-latest # for github-hosted runner
    runs-on: self-hosted # for self-hosted runner (aws)
    steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/student-go-api:v1.0.0
                # tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
